export const CliErrorCode = {
  ArchivedHardDeleteForbidden: "archived_hard_delete_forbidden",
  ArtifactReadFailed: "artifact_read_failed",
  ArtifactWriteRejected: "artifact_write_rejected",
  CiNotPassed: "ci_not_passed",
  CloseoutNotReady: "closeout_not_ready",
  CloseoutPlaceholder: "closeout_placeholder",
  CompletionGateFailed: "completion_gate_failed",
  ConflictingDeleteMode: "conflicting_delete_mode",
  ConflictMarkerPresent: "conflict_marker_present",
  ConflictingGovernanceMode: "conflicting_governance_mode",
  ConflictingLessonMode: "conflicting_lesson_mode",
  ConflictingMigrationMode: "conflicting_migration_mode",
  ConflictingSupersedeTarget: "conflicting_supersede_target",
  CommandReceiptContractMismatch: "command_receipt_contract_mismatch",
  CustomVerticalContractMissing: "custom_vertical_contract_missing",
  CustomVerticalProjectGateRequired: "custom_vertical_project_gate_required",
  CustomVerticalUserDevModeRequired: "custom_vertical_user_dev_mode_required",
  DecodeFailed: "decode_failed",
  DecisionReadFailed: "decision_read_failed",
  DecisionWriteRejected: "decision_write_rejected",
  DeleteConfirmMismatch: "delete_confirm_mismatch",
  DeleteConfirmRequired: "delete_confirm_required",
  DocmapInvalid: "docmap_invalid",
  DuplicateAdoptClaim: "duplicate_adopt_claim",
  DuplicateExternalBinding: "duplicate_external_binding",
  FactWriteRejected: "fact_write_rejected",
  EngineOwnsStatus: "engine_owns_status",
  FullCutoverRetired: "full_cutover_retired",
  GeneratedTaskIdRequired: "generated_task_id_required",
  GitDiffUnavailable: "git_diff_unavailable",
  HarnessSettingsInvalid: "harness_settings_invalid",
  InvalidCheckProfile: "invalid_check_profile",
  InvalidCiGate: "invalid_ci_gate",
  InvalidDecisionActor: "invalid_decision_actor",
  InvalidDecisionEvidenceRelation: "invalid_decision_evidence_relation",
  InvalidDecisionTier: "invalid_decision_tier",
  InvalidEntrypoint: "invalid_entrypoint",
  InvalidEvidence: "invalid_evidence",
  InvalidFactConfidence: "invalid_fact_confidence",
  InvalidFactId: "invalid_fact_id",
  InvalidFactMemoryClass: "invalid_fact_memory_class",
  InvalidFactMemoryTag: "invalid_fact_memory_tag",
  InvalidLessonFilter: "invalid_lesson_filter",
  InvalidLocale: "invalid_locale",
  InvalidModuleStepState: "invalid_module_step_state",
  InvalidRegistryKey: "invalid_registry_key",
  InvalidRuntimeEventKind: "invalid_runtime_event_kind",
  InvalidRuntimeEventValue: "invalid_runtime_event_value",
  InvalidScriptFilter: "invalid_script_filter",
  InvalidStatus: "invalid_status",
  InvalidTransition: "invalid_transition",
  JournalUnavailable: "journal_unavailable",
  LegacyCollisionReportInvalid: "legacy_collision_report_invalid",
  LegacyDuplicateTarget: "legacy_duplicate_target",
  LegacyEntryNotFound: "legacy_entry_not_found",
  LegacyIndexInvalid: "legacy_index_invalid",
  LegacyIndexMissing: "legacy_index_missing",
  LegacyIndexSchemaInvalid: "legacy_index_schema_invalid",
  LegacyIndexTargetsMissing: "legacy_index_targets_missing",
  LegacyRebuildManualIdForbidden: "legacy_rebuild_manual_id_forbidden",
  LegacyRebuildPresetForbidden: "legacy_rebuild_preset_forbidden",
  LegacyStoredPathMissing: "legacy_stored_path_missing",
  LegacyUnsafeSource: "legacy_unsafe_source",
  LessonCandidateNotFound: "lesson_candidate_not_found",
  LessonCandidateNotPromotable: "lesson_candidate_not_promotable",
  LessonCandidatesMissing: "lesson_candidates_missing",
  MalformedSnapshot: "malformed_snapshot",
  ManualTaskIdForbidden: "manual_task_id_forbidden",
  MilestoneCloseoutBlocked: "milestone_closeout_blocked",
  MissingCiGate: "missing_ci_gate",
  MissingDecisionChoice: "missing_decision_choice",
  MissingDecisionQuestion: "missing_decision_question",
  MissingDecisionRejected: "missing_decision_rejected",
  MissingDeleteMode: "missing_delete_mode",
  MissingFactSource: "missing_fact_source",
  MissingFactStatement: "missing_fact_statement",
  MissingForceReason: "missing_force_reason",
  MissingLegacyId: "missing_legacy_id",
  MissingModule: "missing_module",
  MissingModuleFields: "missing_module_fields",
  MissingName: "missing_name",
  MissingPreset: "missing_preset",
  MissingProfile: "missing_profile",
  MissingReason: "missing_reason",
  MissingSession: "missing_session",
  MissingSupersedeTarget: "missing_supersede_target",
  MissingTask: "missing_task",
  MissingTaskId: "missing_task_id",
  MissingText: "missing_text",
  MissingTitle: "missing_title",
  MissingVertical: "missing_vertical",
  ModuleNotFound: "module_not_found",
  PlanConfirmationRequired: "plan_confirmation_required",
  PresetActionForbidden: "preset_action_forbidden",
  PresetManifestInvalid: "preset_manifest_invalid",
  PresetMaterializationFailed: "preset_materialization_failed",
  PresetNotFound: "preset_not_found",
  PresetReadScopeInvalid: "preset_read_scope_invalid",
  PresetReadScopeViolation: "preset_read_scope_violation",
  PresetScriptAuthorizationRequired: "preset_script_authorization_required",
  PresetScriptFailed: "preset_script_failed",
  PresetScriptNotFound: "preset_script_not_found",
  PresetScriptResultFailed: "preset_script_result_failed",
  PresetScriptResultInvalid: "preset_script_result_invalid",
  PresetWriteScopeInvalid: "preset_write_scope_invalid",
  PresetWriteScopeViolation: "preset_write_scope_violation",
  ScriptContractInvalid: "script_contract_invalid",
  ScriptDeclaredProduceMismatch: "script_declared_produce_mismatch",
  ScriptFailed: "script_failed",
  ScriptNotFound: "script_not_found",
  ScriptResultFailed: "script_result_failed",
  ScriptResultInvalid: "script_result_invalid",
  ScriptScopeInvalidRead: "script_scope_invalid_read",
  ScriptScopeInvalidWrite: "script_scope_invalid_write",
  ScriptScopeViolationRead: "script_scope_violation_read",
  ScriptScopeViolationWrite: "script_scope_violation_write",
  RelatedTaskHardDeleteForbidden: "related_task_hard_delete_forbidden",
  ReleaseBlockingFindings: "release_blocking_findings",
  ReviewDocumentMissing: "review_document_missing",
  ReviewNotPassed: "review_not_passed",
  ReviewPlaceholder: "review_placeholder",
  ReviewSchemaInvalid: "review_schema_invalid",
  RuntimeEventLedgerRejected: "runtime_event_ledger_rejected",
  StaleSnapshotRefused: "stale_snapshot_refused",
  StatusCheckFailed: "status_check_failed",
  SupersedeConfirmMismatch: "supersede_confirm_mismatch",
  SupersedeConfirmRequired: "supersede_confirm_required",
  SupersedeTargetNotFound: "supersede_target_not_found",
  TaskAlreadyExists: "task_already_exists",
  TaskNotFound: "task_not_found",
  TemplateCatalogInvalid: "template_catalog_invalid",
  TemplateRenderFailed: "template_render_failed",
  TerminalHardDeleteForbidden: "terminal_hard_delete_forbidden",
  TerminalReopenRequiresSupersede: "terminal_reopen_requires_supersede",
  TerminalStatusRequiresTaskComplete: "terminal_status_requires_task_complete",
  UnknownCommand: "unknown_command",
  UnknownHelpTopic: "unknown_help_topic",
  UserSettingsInvalid: "user_settings_invalid",
  VerticalDefinitionInvalid: "vertical_definition_invalid",
  WriteConflict: "write_conflict",
  WriteRejected: "write_rejected",
  EngineNotEnabled: "EngineNotEnabled",
  AdapterUnavailable: "AdapterUnavailable",
  AuthMissing: "AuthMissing",
  CheckProfileFailed: "check_profile_failed",
  RefNotFound: "RefNotFound",
  ProjectionCheckFailed: "projection_check_failed",
  StatusUnmapped: "StatusUnmapped",
  RateLimited: "RateLimited",
  EngineUnreachable: "EngineUnreachable",
  Timeout: "Timeout"
} as const;

export type CliErrorCode = (typeof CliErrorCode)[keyof typeof CliErrorCode];

export type CliErrorCategory = "parse" | "command" | "domain" | "settings" | "extension" | "migration";
export type CliErrorFamily = "kernel-mapped" | "command-local";

export const cliKernelMappedErrorCodes = new Set<CliErrorCode>([
  CliErrorCode.ArchivedHardDeleteForbidden,
  CliErrorCode.ArtifactReadFailed,
  CliErrorCode.ArtifactWriteRejected,
  CliErrorCode.DuplicateAdoptClaim,
  CliErrorCode.DuplicateExternalBinding,
  CliErrorCode.EngineOwnsStatus,
  CliErrorCode.GeneratedTaskIdRequired,
  CliErrorCode.InvalidTransition,
  CliErrorCode.JournalUnavailable,
  CliErrorCode.MalformedSnapshot,
  CliErrorCode.RelatedTaskHardDeleteForbidden,
  CliErrorCode.StaleSnapshotRefused,
  CliErrorCode.TaskAlreadyExists,
  CliErrorCode.TaskNotFound,
  CliErrorCode.TerminalHardDeleteForbidden,
  CliErrorCode.TerminalReopenRequiresSupersede,
  CliErrorCode.WriteConflict,
  CliErrorCode.WriteRejected,
  CliErrorCode.EngineNotEnabled,
  CliErrorCode.AdapterUnavailable,
  CliErrorCode.AuthMissing,
  CliErrorCode.RefNotFound,
  CliErrorCode.StatusUnmapped,
  CliErrorCode.RateLimited,
  CliErrorCode.EngineUnreachable,
  CliErrorCode.Timeout
]);

export const cliCommandLocalErrorCodes = new Set<CliErrorCode>(
  Object.values(CliErrorCode).filter((code): code is CliErrorCode => !cliKernelMappedErrorCodes.has(code as CliErrorCode))
);

export interface CliError {
  readonly code: CliErrorCode;
  readonly hint: string;
}

export interface CliErrorCodeDefinition {
  readonly category: CliErrorCategory;
  readonly defaultHint: string;
}

export const cliErrorCodeRegistry = {
  [CliErrorCode.ArchivedHardDeleteForbidden]: { category: "domain", defaultHint: "Archived tasks cannot be hard deleted." },
  [CliErrorCode.ArtifactReadFailed]: { category: "domain", defaultHint: "Artifact read failed." },
  [CliErrorCode.ArtifactWriteRejected]: { category: "domain", defaultHint: "Artifact write was rejected." },
  [CliErrorCode.CiNotPassed]: { category: "command", defaultHint: "CI gate has not passed." },
  [CliErrorCode.CloseoutNotReady]: { category: "command", defaultHint: "Closeout is not ready." },
  [CliErrorCode.CloseoutPlaceholder]: { category: "command", defaultHint: "Closeout still contains template placeholder text." },
  [CliErrorCode.CompletionGateFailed]: { category: "command", defaultHint: "Completion gate failed." },
  [CliErrorCode.ConflictingDeleteMode]: { category: "parse", defaultHint: "Use exactly one task delete mode." },
  [CliErrorCode.ConflictMarkerPresent]: { category: "command", defaultHint: "Resolve Git conflict markers before running this command." },
  [CliErrorCode.ConflictingGovernanceMode]: { category: "parse", defaultHint: "Use exactly one governance rebuild mode." },
  [CliErrorCode.ConflictingLessonMode]: { category: "parse", defaultHint: "Use exactly one lesson command mode." },
  [CliErrorCode.ConflictingMigrationMode]: { category: "parse", defaultHint: "Use exactly one migration mode." },
  [CliErrorCode.ConflictingSupersedeTarget]: { category: "parse", defaultHint: "Use exactly one supersede target." },
  [CliErrorCode.CommandReceiptContractMismatch]: { category: "command", defaultHint: "Command receipt contract mismatch." },
  [CliErrorCode.CustomVerticalContractMissing]: { category: "settings", defaultHint: "Custom vertical contract is missing." },
  [CliErrorCode.CustomVerticalProjectGateRequired]: { category: "settings", defaultHint: "Project settings must enable custom verticals." },
  [CliErrorCode.CustomVerticalUserDevModeRequired]: { category: "settings", defaultHint: "User settings must enable custom vertical development mode." },
  [CliErrorCode.DecodeFailed]: { category: "extension", defaultHint: "Registry value failed to decode." },
  [CliErrorCode.DecisionReadFailed]: { category: "command", defaultHint: "Decision document could not be read." },
  [CliErrorCode.DecisionWriteRejected]: { category: "command", defaultHint: "Decision write was rejected." },
  [CliErrorCode.DeleteConfirmMismatch]: { category: "command", defaultHint: "Delete confirmation does not match the task id." },
  [CliErrorCode.DeleteConfirmRequired]: { category: "command", defaultHint: "Delete confirmation is required." },
  [CliErrorCode.DocmapInvalid]: { category: "command", defaultHint: "Docmap manifest is invalid." },
  [CliErrorCode.DuplicateAdoptClaim]: { category: "domain", defaultHint: "Adopt claim already exists." },
  [CliErrorCode.DuplicateExternalBinding]: { category: "domain", defaultHint: "External binding already exists." },
  [CliErrorCode.FactWriteRejected]: { category: "command", defaultHint: "Fact write was rejected." },
  [CliErrorCode.EngineOwnsStatus]: { category: "domain", defaultHint: "Status is owned by an external engine." },
  [CliErrorCode.FullCutoverRetired]: { category: "migration", defaultHint: "Full cutover command is retired." },
  [CliErrorCode.GeneratedTaskIdRequired]: { category: "domain", defaultHint: "Generated task id is required." },
  [CliErrorCode.GitDiffUnavailable]: { category: "command", defaultHint: "Git diff evidence is unavailable." },
  [CliErrorCode.HarnessSettingsInvalid]: { category: "settings", defaultHint: "Project harness settings are invalid." },
  [CliErrorCode.InvalidCheckProfile]: { category: "parse", defaultHint: "Unknown check profile." },
  [CliErrorCode.InvalidCiGate]: { category: "parse", defaultHint: "Unknown CI gate value." },
  [CliErrorCode.InvalidDecisionActor]: { category: "parse", defaultHint: "Decision actor must be formatted as kind:id." },
  [CliErrorCode.InvalidDecisionEvidenceRelation]: { category: "parse", defaultHint: "Decision evidence relation is invalid." },
  [CliErrorCode.InvalidDecisionTier]: { category: "parse", defaultHint: "Decision tier is invalid." },
  [CliErrorCode.InvalidEntrypoint]: { category: "parse", defaultHint: "Unknown preset entrypoint." },
  [CliErrorCode.InvalidEvidence]: { category: "parse", defaultHint: "Evidence value is invalid." },
  [CliErrorCode.InvalidFactConfidence]: { category: "parse", defaultHint: "Fact confidence is invalid." },
  [CliErrorCode.InvalidFactId]: { category: "parse", defaultHint: "Fact id is invalid." },
  [CliErrorCode.InvalidFactMemoryClass]: { category: "parse", defaultHint: "Fact memory class is invalid." },
  [CliErrorCode.InvalidFactMemoryTag]: { category: "parse", defaultHint: "Fact memory tag is invalid." },
  [CliErrorCode.InvalidLessonFilter]: { category: "parse", defaultHint: "Lesson filter is invalid." },
  [CliErrorCode.InvalidLocale]: { category: "parse", defaultHint: "Locale is invalid." },
  [CliErrorCode.InvalidModuleStepState]: { category: "parse", defaultHint: "Module step state is invalid." },
  [CliErrorCode.InvalidRegistryKey]: { category: "extension", defaultHint: "Registry key is invalid." },
  [CliErrorCode.InvalidRuntimeEventKind]: { category: "parse", defaultHint: "Runtime event kind is invalid." },
  [CliErrorCode.InvalidRuntimeEventValue]: { category: "parse", defaultHint: "Runtime event value is invalid." },
  [CliErrorCode.InvalidScriptFilter]: { category: "parse", defaultHint: "Script filter is invalid." },
  [CliErrorCode.InvalidStatus]: { category: "parse", defaultHint: "Lifecycle status is invalid." },
  [CliErrorCode.InvalidTransition]: { category: "domain", defaultHint: "Lifecycle transition is invalid." },
  [CliErrorCode.JournalUnavailable]: { category: "domain", defaultHint: "Write journal is unavailable." },
  [CliErrorCode.LegacyCollisionReportInvalid]: { category: "migration", defaultHint: "Legacy collision report is invalid." },
  [CliErrorCode.LegacyDuplicateTarget]: { category: "migration", defaultHint: "Legacy index contains duplicate targets." },
  [CliErrorCode.LegacyEntryNotFound]: { category: "migration", defaultHint: "Legacy index entry was not found." },
  [CliErrorCode.LegacyIndexInvalid]: { category: "migration", defaultHint: "Legacy index is invalid." },
  [CliErrorCode.LegacyIndexMissing]: { category: "migration", defaultHint: "Legacy index is missing." },
  [CliErrorCode.LegacyIndexSchemaInvalid]: { category: "migration", defaultHint: "Legacy index schema is invalid." },
  [CliErrorCode.LegacyIndexTargetsMissing]: { category: "migration", defaultHint: "Legacy index targets are missing." },
  [CliErrorCode.LegacyRebuildManualIdForbidden]: { category: "parse", defaultHint: "Legacy rebuild cannot use a manual id." },
  [CliErrorCode.LegacyRebuildPresetForbidden]: { category: "parse", defaultHint: "Legacy rebuild cannot be combined with preset input." },
  [CliErrorCode.LegacyStoredPathMissing]: { category: "migration", defaultHint: "Legacy stored path is missing." },
  [CliErrorCode.LegacyUnsafeSource]: { category: "migration", defaultHint: "Legacy Intake source contains generated or self-owned paths." },
  [CliErrorCode.LessonCandidateNotFound]: { category: "command", defaultHint: "Lesson candidate was not found." },
  [CliErrorCode.LessonCandidateNotPromotable]: { category: "command", defaultHint: "Lesson candidate is not promotable." },
  [CliErrorCode.LessonCandidatesMissing]: { category: "command", defaultHint: "Lesson candidates file is missing." },
  [CliErrorCode.MalformedSnapshot]: { category: "domain", defaultHint: "Snapshot is malformed." },
  [CliErrorCode.ManualTaskIdForbidden]: { category: "parse", defaultHint: "Manual task id is forbidden." },
  [CliErrorCode.MilestoneCloseoutBlocked]: { category: "extension", defaultHint: "Milestone closeout is blocked." },
  [CliErrorCode.MissingCiGate]: { category: "parse", defaultHint: "CI gate is required." },
  [CliErrorCode.MissingDecisionChoice]: { category: "parse", defaultHint: "Decision chosen text is required." },
  [CliErrorCode.MissingDecisionQuestion]: { category: "parse", defaultHint: "Decision question is required." },
  [CliErrorCode.MissingDecisionRejected]: { category: "parse", defaultHint: "Decision rejected alternative is required." },
  [CliErrorCode.MissingDeleteMode]: { category: "parse", defaultHint: "Task delete mode is required." },
  [CliErrorCode.MissingFactSource]: { category: "parse", defaultHint: "Fact source is required." },
  [CliErrorCode.MissingFactStatement]: { category: "parse", defaultHint: "Fact statement is required." },
  [CliErrorCode.MissingForceReason]: { category: "parse", defaultHint: "Force reason is required." },
  [CliErrorCode.MissingLegacyId]: { category: "parse", defaultHint: "Legacy id is required." },
  [CliErrorCode.MissingModule]: { category: "parse", defaultHint: "Module key is required." },
  [CliErrorCode.MissingModuleFields]: { category: "parse", defaultHint: "Module title and scope are required." },
  [CliErrorCode.MissingName]: { category: "parse", defaultHint: "Name is required." },
  [CliErrorCode.MissingPreset]: { category: "parse", defaultHint: "Preset id is required." },
  [CliErrorCode.MissingProfile]: { category: "parse", defaultHint: "Profile id is required." },
  [CliErrorCode.MissingReason]: { category: "parse", defaultHint: "Reason is required." },
  [CliErrorCode.MissingSession]: { category: "parse", defaultHint: "Session id is required." },
  [CliErrorCode.MissingSupersedeTarget]: { category: "parse", defaultHint: "Supersede target is required." },
  [CliErrorCode.MissingTask]: { category: "parse", defaultHint: "Task id is required." },
  [CliErrorCode.MissingTaskId]: { category: "parse", defaultHint: "Task id is required." },
  [CliErrorCode.MissingText]: { category: "parse", defaultHint: "Text is required." },
  [CliErrorCode.MissingTitle]: { category: "parse", defaultHint: "Task title is required." },
  [CliErrorCode.MissingVertical]: { category: "parse", defaultHint: "Vertical id is required." },
  [CliErrorCode.ModuleNotFound]: { category: "extension", defaultHint: "Module was not found." },
  [CliErrorCode.PlanConfirmationRequired]: { category: "migration", defaultHint: "Plan confirmation is required." },
  [CliErrorCode.PresetActionForbidden]: { category: "extension", defaultHint: "Preset action is not declared." },
  [CliErrorCode.PresetManifestInvalid]: { category: "extension", defaultHint: "Preset manifest failed validation." },
  [CliErrorCode.PresetMaterializationFailed]: { category: "extension", defaultHint: "Preset materialization failed." },
  [CliErrorCode.PresetNotFound]: { category: "extension", defaultHint: "Preset was not found." },
  [CliErrorCode.PresetReadScopeInvalid]: { category: "extension", defaultHint: "Preset script read scope is invalid." },
  [CliErrorCode.PresetReadScopeViolation]: { category: "extension", defaultHint: "Preset script read scope was violated." },
  [CliErrorCode.PresetScriptAuthorizationRequired]: { category: "extension", defaultHint: "Preset script authorization is required." },
  [CliErrorCode.PresetScriptFailed]: { category: "extension", defaultHint: "Preset script failed." },
  [CliErrorCode.PresetScriptNotFound]: { category: "extension", defaultHint: "Preset script was not found." },
  [CliErrorCode.PresetScriptResultFailed]: { category: "extension", defaultHint: "Preset script reported failure." },
  [CliErrorCode.PresetScriptResultInvalid]: { category: "extension", defaultHint: "Preset script result is invalid." },
  [CliErrorCode.PresetWriteScopeInvalid]: { category: "extension", defaultHint: "Preset script write scope is invalid." },
  [CliErrorCode.PresetWriteScopeViolation]: { category: "extension", defaultHint: "Preset script write scope was violated." },
  [CliErrorCode.ScriptContractInvalid]: { category: "extension", defaultHint: "Script contract is invalid." },
  [CliErrorCode.ScriptDeclaredProduceMismatch]: { category: "extension", defaultHint: "Script produced files outside its declared outputs." },
  [CliErrorCode.ScriptFailed]: { category: "extension", defaultHint: "Script execution failed." },
  [CliErrorCode.ScriptNotFound]: { category: "extension", defaultHint: "Script was not found." },
  [CliErrorCode.ScriptResultFailed]: { category: "extension", defaultHint: "Script reported a failed result." },
  [CliErrorCode.ScriptResultInvalid]: { category: "extension", defaultHint: "Script result is invalid." },
  [CliErrorCode.ScriptScopeInvalidRead]: { category: "extension", defaultHint: "Script read scope is invalid." },
  [CliErrorCode.ScriptScopeInvalidWrite]: { category: "extension", defaultHint: "Script write scope is invalid." },
  [CliErrorCode.ScriptScopeViolationRead]: { category: "extension", defaultHint: "Script read scope was violated." },
  [CliErrorCode.ScriptScopeViolationWrite]: { category: "extension", defaultHint: "Script write scope was violated." },
  [CliErrorCode.RelatedTaskHardDeleteForbidden]: { category: "domain", defaultHint: "Related tasks cannot be hard deleted." },
  [CliErrorCode.ReleaseBlockingFindings]: { category: "command", defaultHint: "Release-blocking findings remain open." },
  [CliErrorCode.ReviewDocumentMissing]: { category: "command", defaultHint: "Review document is missing." },
  [CliErrorCode.ReviewNotPassed]: { category: "command", defaultHint: "Review gate has not passed." },
  [CliErrorCode.ReviewPlaceholder]: { category: "command", defaultHint: "Review still contains the initial placeholder state." },
  [CliErrorCode.ReviewSchemaInvalid]: { category: "command", defaultHint: "Review schema is invalid." },
  [CliErrorCode.RuntimeEventLedgerRejected]: { category: "command", defaultHint: "Runtime event ledger write or read was rejected." },
  [CliErrorCode.StaleSnapshotRefused]: { category: "domain", defaultHint: "Stale snapshot was refused." },
  [CliErrorCode.StatusCheckFailed]: { category: "command", defaultHint: "Status check failed." },
  [CliErrorCode.SupersedeConfirmMismatch]: { category: "command", defaultHint: "Supersede confirmation does not match." },
  [CliErrorCode.SupersedeConfirmRequired]: { category: "command", defaultHint: "Supersede confirmation is required." },
  [CliErrorCode.SupersedeTargetNotFound]: { category: "command", defaultHint: "Supersede target was not found." },
  [CliErrorCode.TaskAlreadyExists]: { category: "domain", defaultHint: "Task already exists." },
  [CliErrorCode.TaskNotFound]: { category: "domain", defaultHint: "Task was not found." },
  [CliErrorCode.TemplateCatalogInvalid]: { category: "extension", defaultHint: "Template catalog is invalid." },
  [CliErrorCode.TemplateRenderFailed]: { category: "extension", defaultHint: "Template render failed." },
  [CliErrorCode.TerminalHardDeleteForbidden]: { category: "domain", defaultHint: "Terminal tasks cannot be hard deleted." },
  [CliErrorCode.TerminalReopenRequiresSupersede]: { category: "domain", defaultHint: "Terminal tasks require supersede to reopen." },
  [CliErrorCode.TerminalStatusRequiresTaskComplete]: { category: "command", defaultHint: "Terminal status changes require task-complete." },
  [CliErrorCode.UnknownCommand]: { category: "parse", defaultHint: "Unknown command." },
  [CliErrorCode.UnknownHelpTopic]: { category: "parse", defaultHint: "Unknown help topic." },
  [CliErrorCode.UserSettingsInvalid]: { category: "settings", defaultHint: "User settings are invalid." },
  [CliErrorCode.VerticalDefinitionInvalid]: { category: "extension", defaultHint: "Vertical definition is invalid." },
  [CliErrorCode.WriteConflict]: { category: "domain", defaultHint: "Write conflict." },
  [CliErrorCode.WriteRejected]: { category: "domain", defaultHint: "Write was rejected." },
  [CliErrorCode.EngineNotEnabled]: { category: "domain", defaultHint: "Engine is not enabled." },
  [CliErrorCode.AdapterUnavailable]: { category: "domain", defaultHint: "Adapter is unavailable." },
  [CliErrorCode.AuthMissing]: { category: "domain", defaultHint: "Authentication is missing." },
  [CliErrorCode.CheckProfileFailed]: { category: "command", defaultHint: "Check profile failed." },
  [CliErrorCode.RefNotFound]: { category: "domain", defaultHint: "Reference was not found." },
  [CliErrorCode.ProjectionCheckFailed]: { category: "command", defaultHint: "Projection check failed." },
  [CliErrorCode.StatusUnmapped]: { category: "domain", defaultHint: "Status is unmapped." },
  [CliErrorCode.RateLimited]: { category: "domain", defaultHint: "Engine request was rate limited." },
  [CliErrorCode.EngineUnreachable]: { category: "domain", defaultHint: "Engine is unreachable." },
  [CliErrorCode.Timeout]: { category: "domain", defaultHint: "Operation timed out." }
} satisfies Record<CliErrorCode, CliErrorCodeDefinition>;

export function cliError(code: CliErrorCode, hint?: string): CliError {
  return { code, hint: hint ?? cliErrorCodeRegistry[code].defaultHint };
}

export function isCliErrorCode(value: unknown): value is CliErrorCode {
  return typeof value === "string" && Object.hasOwn(cliErrorCodeRegistry, value);
}

export function cliErrorFamily(code: CliErrorCode): CliErrorFamily {
  return cliKernelMappedErrorCodes.has(code) ? "kernel-mapped" : "command-local";
}

export function missingRequiredOptionErrorCode(name: string): CliErrorCode {
  switch (name) {
    case "--name":
      return CliErrorCode.MissingName;
    case "--module":
      return CliErrorCode.MissingModule;
    case "--preset":
      return CliErrorCode.MissingPreset;
    case "--profile":
      return CliErrorCode.MissingProfile;
    case "--vertical":
      return CliErrorCode.MissingVertical;
    default:
      throw new Error(`Unsupported required option: ${name}`);
  }
}
